name: check
on:
  pull_request:
  push:
    branches: [main]
jobs:
  package:
    runs-on: native
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - run: nix flake check --print-build-logs
